const state = { token: localStorage.getItem('circle-token') || '', user: null, room: 'general', stream: null, client: crypto.randomUUID(), typingTimer: null }
const $ = (s) => document.querySelector(s), messages = $('#messages'), input = $('#message-input'), dialog = $('#profile-dialog')
const api = async (url, body, method = 'POST') => { const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json', ...(state.token && { Authorization: `Bearer ${state.token}` }) }, body: body ? JSON.stringify({ ...body, room: state.room, client: state.client }) : undefined }); const data = response.status === 204 ? {} : await response.json(); if (!response.ok) throw new Error(data.error || 'Something went wrong'); return data }
function authMessage(message, bad = false) { const node = $('#auth-message'); node.textContent = message; node.classList.toggle('bad', bad) }
function initials(name) { return (name || '?')[0].toUpperCase() }
function setUser(user) { state.user = user; $('#profile-name').textContent = user.name || user.email.split('@')[0]; $('#avatar').textContent = initials(user.name || user.email); $('#avatar').style.background = user.color; }
function updateMembers(users) { $('#member-count').textContent = users.length; $('#member-list').innerHTML = ''; users.forEach((user) => { const node = document.createElement('button'); node.className = 'member'; node.type = 'button'; node.disabled = user.id === state.user.id; node.innerHTML = `<span class="avatar"></span><span></span>`; node.querySelector('.avatar').textContent = initials(user.name); node.querySelector('.avatar').style.background = user.color; node.querySelector('span:last-child').textContent = user.name + (user.id === state.user.id ? ' (You)' : ''); node.addEventListener('click', () => openDirect(user)); $('#member-list').append(node) }) }
function openDirect(user) { state.room = `dm:${[state.user.id, user.id].sort().join(':')}`; document.querySelectorAll('.room').forEach((item) => item.classList.remove('active')); $('#room-title').textContent = `@ ${user.name}`; $('#room-description').textContent = 'Private conversation — only you and this member can view it'; input.placeholder = `Message ${user.name}`; loadRoom() }
function reactionMarkup(reactions = {}) { return Object.entries(reactions).filter(([, count]) => count).map(([emoji, count]) => `<button class="reaction" data-emoji="${emoji}">${emoji} <span>${count}</span></button>`).join('') }
function addMessage(item) { if ($(`[data-message-id="${item.id}"]`)) return; const empty = messages.querySelector('.empty'); if (empty) empty.remove(); const article = document.createElement('article'); article.dataset.messageId = item.id; article.className = item.userId === state.user.id ? 'mine' : ''; const date = new Date(item.time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); article.innerHTML = `<span class="avatar"></span><div class="message-body"><b></b><time>${date}</time><p></p><div class="reactions">${reactionMarkup(item.reactions)}</div><div class="react-picker"><button data-emoji="👍">👍</button><button data-emoji="❤️">❤️</button><button data-emoji="😂">😂</button><button data-emoji="🎉">🎉</button></div></div>`; article.querySelector('.avatar').textContent = initials(item.name); article.querySelector('.avatar').style.background = item.color || '#7855d9'; article.querySelector('b').textContent = item.name; article.querySelector('p').textContent = item.text; messages.append(article); messages.scrollTop = messages.scrollHeight }
function updateReaction(data) { const article = $(`[data-message-id="${data.id}"]`); if (article) article.querySelector('.reactions').innerHTML = reactionMarkup(data.reactions) }
messages.addEventListener('click', async (event) => { const button = event.target.closest('[data-emoji]'), article = button?.closest('[data-message-id]'); if (article) try { await api('/react', { id: article.dataset.messageId, emoji: button.dataset.emoji }) } catch (e) { console.error(e) } })
async function loadRoom() { messages.innerHTML = '<div class="empty">Loading messages…</div>'; try { const history = await api(`/messages?room=${encodeURIComponent(state.room)}`, null, 'GET'); messages.innerHTML = ''; history.forEach(addMessage); if (!history.length) messages.innerHTML = '<div class="empty">Welcome! Send the first message 👋</div>'; state.stream?.close(); state.stream = new EventSource(`/events?room=${encodeURIComponent(state.room)}&client=${state.client}&token=${state.token}`); state.stream.addEventListener('message', (event) => addMessage(JSON.parse(event.data))); state.stream.addEventListener('presence', (event) => updateMembers(JSON.parse(event.data))); state.stream.addEventListener('reaction', (event) => updateReaction(JSON.parse(event.data))); state.stream.addEventListener('typing', (event) => { const value = JSON.parse(event.data); $('#typing').textContent = value.active ? `${value.name} is typing…` : '' }) } catch (e) { authMessage(e.message, true); signOut() } }
function showProfile(force = false) { $('#profile-input').value = state.user.name || ''; $('#bio-input').value = state.user.bio || ''; $('#color-input').value = state.user.color || '#7855d9'; dialog.dataset.force = force; $('#profile-form [value="cancel"]').hidden = force; dialog.showModal() }
async function start() { try { const { user } = await api('/me', null, 'GET'); setUser(user); $('#auth-screen').hidden = true; if (!user.name) showProfile(true); else { $('#chat-app').hidden = false; loadRoom() } } catch { signOut(); authMessage('Please sign in to continue.') } }
function signOut() { state.stream?.close(); localStorage.removeItem('circle-token'); state.token = ''; state.user = null; $('#chat-app').hidden = true; $('#auth-screen').hidden = false; }
$('#signup-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const result = await api('/auth/signup', { email: $('#signup-email').value, password: $('#signup-password').value }); $('#verify-form').hidden = false; $('#demo-code').textContent = `Demo verification code: ${result.devCode}`; authMessage('Account created. Enter the verification code.'); $('#verify-code').focus() } catch (e) { authMessage(e.message, true) } })
$('#verify-form').addEventListener('submit', async (event) => { event.preventDefault(); try { await api('/auth/verify', { email: $('#signup-email').value, code: $('#verify-code').value }); authMessage('Email verified. Sign in below.'); $('#login-email').value = $('#signup-email').value } catch (e) { authMessage(e.message, true) } })
$('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const result = await api('/auth/login', { email: $('#login-email').value, password: $('#login-password').value }); state.token = result.token; localStorage.setItem('circle-token', state.token); await start() } catch (e) { authMessage(e.message, true) } })
$('#profile-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const { user } = await api('/profile', { name: $('#profile-input').value, bio: $('#bio-input').value, color: $('#color-input').value }, 'PUT'); setUser(user); dialog.close(); $('#chat-app').hidden = false; loadRoom() } catch (e) { alert(e.message) } })
dialog.addEventListener('cancel', (event) => { if (dialog.dataset.force === 'true') event.preventDefault() })
$('#edit-profile').addEventListener('click', () => showProfile()); $('#logout').addEventListener('click', signOut)
$('#message-form').addEventListener('submit', async (event) => { event.preventDefault(); const text = input.value.trim(); if (!text) return; input.value = ''; try { await api('/messages', { text }); api('/typing', { active: false }) } catch (e) { alert(e.message) } })
input.addEventListener('input', () => { api('/typing', { active: true }).catch(() => {}); clearTimeout(state.typingTimer); state.typingTimer = setTimeout(() => api('/typing', { active: false }).catch(() => {}), 900) })
document.querySelectorAll('.room').forEach((button) => button.addEventListener('click', () => { state.room = button.dataset.room; document.querySelectorAll('.room').forEach((item) => item.classList.toggle('active', item === button)); $('#room-title').textContent = `# ${state.room}`; $('#room-description').textContent = 'Private chat for verified Circle members'; input.placeholder = `Message #${state.room}`; loadRoom() }))
$('#emoji-button').addEventListener('click', () => $('#emoji-menu').toggleAttribute('hidden')); document.querySelectorAll('#emoji-menu button').forEach((button) => button.addEventListener('click', () => { input.value += button.textContent; input.focus(); $('#emoji-menu').hidden = true })); start()
